### PR TITLE
PYIC-3257: Add new f2f error page

### PR DESCRIPTION
**Pull request by AmritSidhu**
### What changed

Added new f2f technical error page
Currently has interim welsh translations 
By having this page now it will allow us to wire everything up in the backend.

### Why did it change

This is the new error page that will be used for f2f. It has specific actions compared to our generic technical error pages.

### Issue tracking

- [PYIC-3257](https://govukverify.atlassian.net/browse/PYIC-3257)

### Environment variables or secrets

- [x] No environment variables or secrets were added or changed

[PYIC-3257]: https://govukverify.atlassian.net/browse/PYIC-3257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by blakeyp — DISMISSED** [review]
(Slack seems to be down?) Looks good, should be fine to merge though maybe wait till the pipeline is unblocked

**Comment by Wynndow** [comment]
Coming here to post a comment to see if Slack is down for other people. Just saw @blakeyp 's comment and relieved it's not just me!

**Comment by blakeyp** [comment]
According to https://status.slack.com/ all is fine 🙃

**Comment by Wynndow** [comment]
I know, weird. Might just be the GDS workspace? GMail has chat, can use that in it's absence.

**Review by blakeyp — APPROVED** [review]

**Pull request merged**
